# This workflow is for:
#   Triggers: any push to dev branch
#   Deployment: none

name: Build

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build